default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: thing_fyi_development
test:
  <<: *default
  database: thing_fyi_test
production:
  <<: *default
  database: thing_fyi_production
